### ISSUE TITLE
Nordic won't load on 1.9

### ISSUE THREAD

**Issue by emash** [s1mpl3x/Nordic#3]
Using latest spigot server Nordic won't load on startup and won't work.
http://pastebin.com/xU9jeMew

**Comment by s1mpl3x** [comment]
https://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0

nordic uses java 8 features, seems like you still run an older jre?

**Comment by emash** [comment]
thank you, installing oracle jre 8 on my debian fixed the problem!
